security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        my_firewall:
            pattern: ^/
            trusted_sso:
                manager: admin_sso
                create_users: true
                login_action: true
                logout_action: true
                login_path: /login
                check_path: /login_check
            provider: fos_userbundle
